enum EmergencyType { fire, medical, security, infrastructure, other }
enum AlertStatus { pending, triaged, acknowledged, inProgress, resolved }

class GeoPoint {
  final double latitude;
  final double longitude;
  
  const GeoPoint(this.latitude, this.longitude);

  factory GeoPoint.fromMap(Map<dynamic, dynamic> map) {
    return GeoPoint(
      (map['latitude'] as num?)?.toDouble() ?? 0.0,
      (map['longitude'] as num?)?.toDouble() ?? 0.0,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'latitude': latitude,
      'longitude': longitude,
    };
  }
}

class Alert {
  String id;               // uuid v4
  String userId;           // Firebase Auth UID
  String venueId;          // venue identifier
  String roomNumber;       // e.g. "412"
  int floor;               // e.g. 4
  String description;      // raw guest input text
  String? imageUrl;        // Firebase Storage URL if photo attached
  EmergencyType? type;     // enum — set by Gemini, initially null
  int? severity;           // 1–5 — set by Gemini, initially null
  GeoPoint location;       // GPS coordinates
  int timestamp;           // Unix milliseconds
  AlertStatus status;      // enum
  List<String> assignedTo; // staff userIds
  String? responderBriefUrl;
  String? language;        // ISO 639-1, detected by Gemini
  String? safetyInstructions; // generated by Gemini
  Map<String, String>? medicalInfo; // Anonymous medical profile
  String? roomKey;         // e.g. "Room_204" — used for room token rejoin

  Alert({
    required this.id,
    required this.userId,
    required this.venueId,
    required this.roomNumber,
    required this.floor,
    required this.description,
    this.imageUrl,
    this.type,
    this.severity,
    required this.location,
    required this.timestamp,
    required this.status,
    required this.assignedTo,
    this.responderBriefUrl,
    this.language,
    this.safetyInstructions,
    this.roomKey,
    this.medicalInfo,
  });

  factory Alert.fromMap(Map<dynamic, dynamic> map) {
    return Alert(
      id: map['id'] as String? ?? '',
      userId: map['userId'] as String? ?? '',
      venueId: map['venueId'] as String? ?? '',
      roomNumber: map['roomNumber'] as String? ?? '',
      floor: (map['floor'] as num?)?.toInt() ?? 0,
      description: map['description'] as String? ?? '',
      imageUrl: map['imageUrl'] as String?,
      type: map['type'] != null ? EmergencyType.values.firstWhere((e) => e.name == map['type'], orElse: () => EmergencyType.other) : null,
      severity: map['severity'] as int?,
      location: map['location'] != null ? GeoPoint.fromMap(map['location'] as Map<dynamic, dynamic>) : const GeoPoint(0.0, 0.0),
      timestamp: (map['timestamp'] as num?)?.toInt() ?? 0,
      status: AlertStatus.values.firstWhere((e) => e.name == map['status'], orElse: () => AlertStatus.pending),
      assignedTo: (map['assignedTo'] as List<dynamic>?)?.map((e) => e.toString()).toList() ?? [],
      responderBriefUrl: map['responderBriefUrl'] as String?,
      language: map['language'] as String?,
      safetyInstructions: map['safetyInstructions'] as String?,
      roomKey: map['roomKey'] as String?,
      medicalInfo: map['medicalInfo'] != null ? Map<String, String>.from(map['medicalInfo'] as Map) : null,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'venueId': venueId,
      'roomNumber': roomNumber,
      'floor': floor,
      'description': description,
      'imageUrl': imageUrl,
      'type': type?.name,
      'severity': severity,
      'location': location.toMap(),
      'timestamp': timestamp,
      'status': status.name,
      'assignedTo': assignedTo,
      'responderBriefUrl': responderBriefUrl,
      'language': language,
      'safetyInstructions': safetyInstructions,
      'roomKey': roomKey,
      'medicalInfo': medicalInfo,
    };
  }
}
