const fs = require('fs');

let content = fs.readFileSync('/home/nkandasamy/Desktop/SwiftServe/guest_app/assets/knowledge/js/translations.js', 'utf8');

const fireTranslations = {
  en: `    "fire_h2_3": "3. If Your Clothes Catch Fire",
    "fire_step1_strong": "Stay Low:",
    "fire_step1_text": " Smoke rises. Crawl or stay as close to the floor as possible to breathe cleaner air.",
    "fire_step2_strong": "Feel Doors:",
    "fire_step2_text": " Before opening any door, feel the handle and the door itself with the back of your hand. If hot, DO NOT OPEN IT. Find another exit.",
    "fire_step3_strong": "Use Stairs:",
    "fire_step3_text": " NEVER use the elevator during a fire. Always use the stairs.",
    "fire_step4_strong": "Seal the Room:",
    "fire_step4_text": " Close all doors between you and the fire. Block cracks under doors with wet towels or clothing to keep smoke out.",
    "fire_step5_strong": "Signal for Help:",
    "fire_step5_text": " Go to a window. Wave a brightly colored cloth or use a flashlight at night to signal responders.",
    "fire_step6_strong": "Stay by the Window:",
    "fire_step6_text": " Do not break the window unless absolutely necessary for air, as it can draw smoke into the room.",
    "fire_step7_strong": "STOP:",
    "fire_step7_text": " Do not run. Running fans the flames.",
    "fire_step8_strong": "DROP:",
    "fire_step8_text": " Drop to the ground immediately.",
    "fire_step9_strong": "ROLL:",
    "fire_step9_text": " Cover your face with your hands and roll back and forth to smother the flames.",`,
  es: `    "fire_h2_3": "3. Si su ropa se incendia",
    "fire_step1_strong": "Manténgase agachado:",
    "fire_step1_text": " El humo sube. Gatee o manténgase lo más cerca posible del suelo para respirar aire más limpio.",
    "fire_step2_strong": "Toque las puertas:",
    "fire_step2_text": " Antes de abrir cualquier puerta, toque la manija y la puerta misma con el dorso de la mano. Si está caliente, NO LA ABRA. Busque otra salida.",
    "fire_step3_strong": "Use las escaleras:",
    "fire_step3_text": " NUNCA use el ascensor durante un incendio. Use siempre las escaleras.",
    "fire_step4_strong": "Selle la habitación:",
    "fire_step4_text": " Cierre todas las puertas entre usted y el fuego. Bloquee las grietas debajo de las puertas con toallas o ropa mojada para que no entre el humo.",
    "fire_step5_strong": "Pida ayuda:",
    "fire_step5_text": " Vaya a una ventana. Agite un paño de colores brillantes o use una linterna por la noche para avisar a los rescatistas.",
    "fire_step6_strong": "Quédese junto a la ventana:",
    "fire_step6_text": " No rompa la ventana a menos que sea absolutamente necesario para respirar, ya que puede atraer humo a la habitación.",
    "fire_step7_strong": "DETÉNGASE:",
    "fire_step7_text": " No corra. Correr aviva las llamas.",
    "fire_step8_strong": "TÍRESE AL SUELO:",
    "fire_step8_text": " Tírese al suelo de inmediato.",
    "fire_step9_strong": "RUEDE:",
    "fire_step9_text": " Cúbrase la cara con las manos y ruede de un lado a otro para sofocar las llamas.",`,
  fr: `    "fire_h2_3": "3. Si vos vêtements prennent feu",
    "fire_step1_strong": "Restez bas :",
    "fire_step1_text": " La fumée monte. Rampez ou restez aussi près du sol que possible pour respirer un air plus pur.",
    "fire_step2_strong": "Touchez les portes :",
    "fire_step2_text": " Avant d'ouvrir une porte, touchez la poignée et la porte avec le dos de votre main. Si c'est chaud, NE L'OUVREZ PAS.",
    "fire_step3_strong": "Utilisez les escaliers :",
    "fire_step3_text": " N'utilisez JAMAIS l'ascenseur pendant un incendie. Utilisez toujours les escaliers.",
    "fire_step4_strong": "Scellez la pièce :",
    "fire_step4_text": " Fermez toutes les portes entre vous et le feu. Bloquez les fissures sous les portes avec des serviettes humides.",
    "fire_step5_strong": "Signalez :",
    "fire_step5_text": " Allez à une fenêtre. Agitez un chiffon de couleur vive.",
    "fire_step6_strong": "Restez près de la fenêtre :",
    "fire_step6_text": " Ne cassez pas la fenêtre sauf si cela est absolument nécessaire.",
    "fire_step7_strong": "ARRÊTEZ-VOUS :",
    "fire_step7_text": " Ne courez pas.",
    "fire_step8_strong": "TOMBEZ :",
    "fire_step8_text": " Tombez au sol immédiatement.",
    "fire_step9_strong": "ROULEZ :",
    "fire_step9_text": " Couvrez votre visage avec vos mains et roulez pour étouffer les flammes.",`,
  hi: `    "fire_h2_3": "3. यदि आपके कपड़ों में आग लग जाए",
    "fire_step1_strong": "नीचे रहें:",
    "fire_step1_text": " धुआं ऊपर उठता है। स्वच्छ हवा लेने के लिए जितना हो सके फर्श के करीब रहें या रेंगें।",
    "fire_step2_strong": "दरवाजों को छुएं:",
    "fire_step2_text": " दरवाजा खोलने से पहले हैंडल को छुएं। यदि यह गर्म है, तो इसे न खोलें।",
    "fire_step3_strong": "सीढ़ियों का उपयोग करें:",
    "fire_step3_text": " कभी भी लिफ्ट का उपयोग न करें। हमेशा सीढ़ियों का उपयोग करें।",
    "fire_step4_strong": "कमरे को सील करें:",
    "fire_step4_text": " अपने और आग के बीच के सभी दरवाजे बंद कर दें। धुएं को रोकने के लिए गीले तौलिये से दरारों को बंद करें।",
    "fire_step5_strong": "मदद के लिए संकेत दें:",
    "fire_step5_text": " एक खिड़की पर जाएं और चमकीले रंग का कपड़ा हिलाएं।",
    "fire_step6_strong": "खिड़की के पास रहें:",
    "fire_step6_text": " खिड़की को तब तक न तोड़ें जब तक कि हवा के लिए बिल्कुल आवश्यक न हो।",
    "fire_step7_strong": "रुकें:",
    "fire_step7_text": " दौड़ें नहीं।",
    "fire_step8_strong": "गिरें:",
    "fire_step8_text": " तुरंत जमीन पर गिर जाएं।",
    "fire_step9_strong": "रोल करें:",
    "fire_step9_text": " अपने चेहरे को ढक लें और आग बुझाने के लिए रोल करें।",`,
  ta: `    "fire_h2_3": "3. ஆடையில் தீ பிடித்தால்",
    "fire_step1_strong": "கீழே இருக்கவும்:",
    "fire_step1_text": " புகை மேலே எழும்பும். தூய்மையான காற்றை சுவாசிக்க தரையோடு நெருக்கமாக இருக்கவும்.",
    "fire_step2_strong": "கதவுகளை தொடவும்:",
    "fire_step2_text": " கதவை திறக்கும் முன் கையின் பின்புறத்தால் தொட்டு பார்க்கவும். சூடாக இருந்தால் திறக்க வேண்டாம்.",
    "fire_step3_strong": "படிக்கட்டுகளை பயன்படுத்தவும்:",
    "fire_step3_text": " மின் தூக்கியை பயன்படுத்த வேண்டாம். எப்போதும் படிக்கட்டுகளை பயன்படுத்தவும்.",
    "fire_step4_strong": "அறையை மூடவும்:",
    "fire_step4_text": " அனைத்து கதவுகளையும் மூடவும். புகையை தடுக்க ஈரமான துணிகளை பயன்படுத்தவும்.",
    "fire_step5_strong": "உதவி கேட்கவும்:",
    "fire_step5_text": " ஜன்னல் அருகே சென்று பிரகாசமான துணியை அசைக்கவும்.",
    "fire_step6_strong": "ஜன்னல் அருகே இருக்கவும்:",
    "fire_step6_text": " ஜன்னலை உடைக்க வேண்டாம்.",
    "fire_step7_strong": "நிற்க:",
    "fire_step7_text": " ஓட வேண்டாம்.",
    "fire_step8_strong": "கீழே விழ:",
    "fire_step8_text": " உடனடியாக தரையில் விழவும்.",
    "fire_step9_strong": "உருளவும்:",
    "fire_step9_text": " முகத்தை மூடிக்கொண்டு தரையில் உருளவும்.",`
};

for (const lang in fireTranslations) {
  const searchStr = `"fire_h2_3": "${content.match(new RegExp(`"fire_h2_3": "([^"]+)"`))[1]}",`;
  content = content.replace(searchStr, fireTranslations[lang]);
}

fs.writeFileSync('/home/nkandasamy/Desktop/SwiftServe/guest_app/assets/knowledge/js/translations.js', content);
console.log("Updated translations.js with fire_step translations");
